# _config.yml
title: Mi Sitio Web Personal
description: >- # esta línea es opcional
  Esta es la página de inicio de mi proyecto personal en GitHub Pages con un tema personalizado.
baseurl: "" # la subruta de tu sitio, e.g., /blog
url: "" # la URL base de tu sitio, si tienes una

# Cambiar a un tema predeterminado
theme: minima

# Personalización del tema Minima
minima:
  skin: "air" # "air" es una de las pieles proporcionadas por Minima

# Detalles del autor
author:
  name: Salvador
  email: tu-email@example.com

# Redes sociales
social_links:
  twitter: tuusuario
  github: salvador03
  linkedin: tu-usuario-linkedin
  email: tu-email@example.com

# Plugins (https://rubygems.org/search?utf8=%E2%9C%93&query=jekyll-)
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Excluir archivos de la compilación
exclude:
  - README.md
  - node_modules
  - test
  - vendor
